Add ability to fetch number of sequences and I-th sequence from FAI index
rust-bio/rust-htslib pull request #377
Opened 2023-02-23 18:40 UTC by jamorrison

`faidx.c` has two functions for retrieving the number of sequences in the FAI index (`faidx_nseq`) and the name of the I-th sequence (`faidx_iseq`). Previously these two functions weren't accessible through `rust-htslib`. I've added a function to access each of these into the `faidx` module.

This is my first PR for `rust-htslib`, so let me know if there are any things I can improve upon in my code!

2023-03-22 11:17 UTC, johanneskoester requested changes
Thanks! I would rename the functions a bit, see below.

2023-03-22 11:17 UTC, johanneskoester commented on src/faidx/mod.rs
> +    pub fn fetch_n_seqs(&self) -> u64 {
```suggestion
    pub fn n_seqs(&self) -> u64 {
```

2023-03-22 11:17 UTC, johanneskoester commented on src/faidx/mod.rs
> +    pub fn fetch_i_seq(&self, i: i32) -> Result<String> {
```suggestion
    pub fn seq_name(&self, i: i32) -> Result<String> {
```

2023-03-29 02:46 UTC, brentp commented
I need this functionality, anything holding up the PR?

2023-03-29 23:31 UTC, brentp commented
Thanks @brainstorm . 
@jamorrison , you can take my tests nearly verbatim from #381

2023-03-30 00:21 UTC, jamorrison commented
Thanks @brentp for the test code!

@johanneskoester I've added added tests for the two functions in the PR. Let me know if there's further work that needs to be done to wrap up this PR.

2023-03-30 08:53 UTC, johanneskoester approved these changes

2023-03-30 08:53 UTC, johanneskoester approved these changes

2023-03-30 08:53 UTC, merged