Add rust_htslib::bcf::index::build
rust-bio/rust-htslib pull request #408
Opened 2023-09-28 20:12 UTC by PB-DB

Builds a bcf/vcf index using the htslib bindings. It was useful to us, so I'm happy to share.

It's modeled after the equivalent in `rust_htslib::bam::index`. I've used it myself to verify behavior, but I haven't built any doc or unit tests.

Hope it's helpful!

Best,

Daniel

2023-12-14 22:10 UTC, johanneskoester approved these changes
Thanks!

2023-12-14 22:11 UTC, johanneskoester requested changes
Can you please add a test case?

2023-12-15 17:13 UTC, PB-DB commented
Sure!

I added some basic tests for successful construction from bcf + vcf.gz, as well as assert errors on building the wrong index format.

It would be convenient if it automatically chose 14 for a min shift for CSI files, or if we autodetected the index type to build, but I'm not sure it would make sense for the library. I'm happy to if you think it's worth it.

Thanks for building such a great resource!

2023-12-18 11:25 UTC, johanneskoester commented
> Sure!
> 
> I added some basic tests for successful construction from bcf + vcf.gz, as well as assert errors on building the wrong index format.
> 
> It would be convenient if it automatically chose 14 for a min shift for CSI files, or if we autodetected the index type to build, but I'm not sure it would make sense for the library. I'm happy to if you think it's worth it.
> 
> Thanks for building such a great resource!

Sure, feel free to extend the functionality in that direction in a follow-up PR! And thanks for liking rust-htslib!

2024-02-23 14:57 UTC, johanneskoester commented
May I ask you to update to merge in the latest upstream master branch? It contains fixes for the failing tests.

2024-02-23 16:40 UTC, PB-DB commented
Done - and thanks for figuring that out. Hope this fixes the tests! 🤞

2024-03-27 14:38 UTC, johanneskoester approved these changes

2024-03-27 14:39 UTC, merged